<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Surah;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['nama' => 'Al-Fatihah', 'total_ayat' => 7],
            ['nama' => 'Al-Baqarah', 'total_ayat' => 286],
            ['nama' => 'Ali Imran', 'total_ayat' => 200],
            ['nama' => 'An-Nisa', 'total_ayat' => 176],
            ['nama' => "Al-Ma'idah", 'total_ayat' => 120],
            ['nama' => "Al-An'am", 'total_ayat' => 165],
            ['nama' => "Al-A'raf", 'total_ayat' => 206],
            ['nama' => 'Al-Anfal', 'total_ayat' => 75],
            ['nama' => 'At-Tawbah', 'total_ayat' => 129],
            ['nama' => 'Yunus', 'total_ayat' => 109],
            ['nama' => 'Hud', 'total_ayat' => 123],
            ['nama' => 'Yusuf', 'total_ayat' => 111],
            ['nama' => 'Ar-Rad', 'total_ayat' => 43],
            ['nama' => 'Ibrahim', 'total_ayat' => 52],
            ['nama' => 'Al-Hijr', 'total_ayat' => 99],
            ['nama' => 'An-Nahl', 'total_ayat' => 128],
            ['nama' => 'Al-Isra', 'total_ayat' => 111],
            ['nama' => 'Al-Kahf', 'total_ayat' => 110],
            ['nama' => 'Maryam', 'total_ayat' => 98],
            ['nama' => 'Ta-Ha', 'total_ayat' => 135],
            ['nama' => 'Al-Anbiya', 'total_ayat' => 112],
            ['nama' => 'Al-Hajj', 'total_ayat' => 78],
            ['nama' => 'Al-Muminun', 'total_ayat' => 118],
            ['nama' => 'An-Nur', 'total_ayat' => 64],
            ['nama' => 'Al-Furqan', 'total_ayat' => 77],
            ['nama' => 'Ash-Shuara', 'total_ayat' => 227],
            ['nama' => 'An-Naml', 'total_ayat' => 93],
            ['nama' => 'Al-Qasas', 'total_ayat' => 88],
            ['nama' => 'Al-Ankabut', 'total_ayat' => 69],
            ['nama' => 'Ar-Rum', 'total_ayat' => 60],
            ['nama' => 'Luqman', 'total_ayat' => 34],
            ['nama' => 'As-Sajdah', 'total_ayat' => 30],
            ['nama' => 'Al-Ahzab', 'total_ayat' => 73],
            ['nama' => 'Saba', 'total_ayat' => 54],
            ['nama' => 'Fatir', 'total_ayat' => 45],
            ['nama' => 'Yasin', 'total_ayat' => 83],
            ['nama' => 'As-Saffat', 'total_ayat' => 182],
            ['nama' => 'Sad', 'total_ayat' => 88],
            ['nama' => 'Az-Zumar', 'total_ayat' => 75],
            ['nama' => 'Ghafir', 'total_ayat' => 85],
            ['nama' => 'Fussilat', 'total_ayat' => 54],
            ['nama' => 'Ash-Shura', 'total_ayat' => 53],
            ['nama' => 'Az-Zukhruf', 'total_ayat' => 89],
            ['nama' => 'Ad-Dukhan', 'total_ayat' => 59],
            ['nama' => 'Al-Jathiyah', 'total_ayat' => 37],
            ['nama' => 'Al-Ahqaf', 'total_ayat' => 35],
            ['nama' => 'Muhammad', 'total_ayat' => 38],
            ['nama' => 'Al-Fath', 'total_ayat' => 29],
            ['nama' => 'Al-Hujurat', 'total_ayat' => 18],
            ['nama' => 'Qaf', 'total_ayat' => 45],
            ['nama' => 'Adh-Dhariyat', 'total_ayat' => 60],
            ['nama' => 'At-Tur', 'total_ayat' => 49],
            ['nama' => 'An-Najm', 'total_ayat' => 62],
            ['nama' => 'Al-Qamar', 'total_ayat' => 55],
            ['nama' => 'Ar-Rahman', 'total_ayat' => 78],
            ['nama' => 'Al-Waqiah', 'total_ayat' => 96],
            ['nama' => 'Al-Hadid', 'total_ayat' => 29],
            ['nama' => 'Al-Mujadila', 'total_ayat' => 22],
            ['nama' => 'Al-Hashr', 'total_ayat' => 24],
            ['nama' => 'Al-Mumtahanah', 'total_ayat' => 13],
            ['nama' => 'As-Saff', 'total_ayat' => 14],
            ['nama' => 'Al-Jumuah', 'total_ayat' => 11],
            ['nama' => 'Al-Munafiqun', 'total_ayat' => 11],
            ['nama' => 'At-Taghabun', 'total_ayat' => 18],
            ['nama' => 'At-Talaq', 'total_ayat' => 12],
            ['nama' => 'At-Tahrim', 'total_ayat' => 12],
            ['nama' => 'Al-Mulk', 'total_ayat' => 30],
            ['nama' => 'Al-Qalam', 'total_ayat' => 52],
            ['nama' => 'Al-Haqqah', 'total_ayat' => 52],
            ['nama' => 'Al-Maarij', 'total_ayat' => 44],
            ['nama' => 'Nuh', 'total_ayat' => 28],
            ['nama' => 'Al-Jinn', 'total_ayat' => 28],
            ['nama' => 'Al-Muzzammil', 'total_ayat' => 20],
            ['nama' => 'Al-Muddaththir', 'total_ayat' => 56],
            ['nama' => 'Al-Qiyamah', 'total_ayat' => 40],
            ['nama' => 'Al-Insan', 'total_ayat' => 31],
            ['nama' => 'Al-Mursalat', 'total_ayat' => 50],
            ['nama' => 'An-Naba', 'total_ayat' => 40],
            ['nama' => 'An-Naziat', 'total_ayat' => 46],
            ['nama' => 'Abasa', 'total_ayat' => 42],
            ['nama' => 'At-Takwir', 'total_ayat' => 29],
            ['nama' => 'Al-Infitar', 'total_ayat' => 19],
            ['nama' => 'Al-Mutaffifin', 'total_ayat' => 36],
            ['nama' => 'Al-Inshiqaq', 'total_ayat' => 25],
            ['nama' => 'Al-Buruj', 'total_ayat' => 22],
            ['nama' => 'At-Tariq', 'total_ayat' => 17],
            ['nama' => 'Al-Ala', 'total_ayat' => 19],
            ['nama' => 'Al-Ghashiyah', 'total_ayat' => 26],
            ['nama' => 'Al-Fajr', 'total_ayat' => 30],
            ['nama' => 'Al-Balad', 'total_ayat' => 20],
            ['nama' => 'Ash-Shams', 'total_ayat' => 15],
            ['nama' => 'Al-Lail', 'total_ayat' => 21],
            ['nama' => 'Ad-Duha', 'total_ayat' => 11],
            ['nama' => 'Ash-Sharh', 'total_ayat' => 8],
            ['nama' => 'At-Tin', 'total_ayat' => 8],
            ['nama' => 'Al-Alaq', 'total_ayat' => 19],
            ['nama' => 'Al-Qadr', 'total_ayat' => 5],
            ['nama' => 'Al-Bayyinah', 'total_ayat' => 8],
            ['nama' => 'Az-Zalzalah', 'total_ayat' => 8],
            ['nama' => 'Al-Adiyat', 'total_ayat' => 11],
            ['nama' => 'Al-Qariah', 'total_ayat' => 11],
            ['nama' => 'At-Takathur', 'total_ayat' => 8],
            ['nama' => 'Al-Asr', 'total_ayat' => 3],
            ['nama' => 'Al-Humazah', 'total_ayat' => 9],
            ['nama' => 'Al-Fil', 'total_ayat' => 5],
            ['nama' => 'Quraisy', 'total_ayat' => 4],
            ['nama' => 'Al-Maun', 'total_ayat' => 7],
            ['nama' => 'Al-Kawthar', 'total_ayat' => 3],
            ['nama' => 'Al-Kafirun', 'total_ayat' => 6],
            ['nama' => 'An-Nasr', 'total_ayat' => 3],
            ['nama' => 'Al-Lahab', 'total_ayat' => 5],
            ['nama' => 'Al-Ikhlas', 'total_ayat' => 4],
            ['nama' => 'Al-Falaq', 'total_ayat' => 5],
            ['nama' => 'An-Nas', 'total_ayat' => 6],
        ];

        foreach ($surahs as $surah) {
            Surah::create($surah);
        }
    }
}
